### PR TITLE
add option on how to merge env var from system

### PR DESCRIPTION
**Pull request by Platane**
Since the plugin use whatever it founds on the process.env, I was afraid of leaking secret into my bundle.

This PR add option to either restrict the var replaced to the ones in .env, or to not use system env var at all.

It's quite a big change, and may need some discussion.

The default option is the current behaviour, no breaking change here.

One thing that did change, is that this plugin no longer fill the process.env with the content of the .dotenv file. Which I think is better since it's an undocumented side effect. But it might break packages which unknowingly relies on this.

### CODE REVIEW

**Comment by brysgo** [comment]
@Platane - This is a great idea and I support it, I will need some time to review this and get back to you. Thank you for your contribution!

**Comment by brysgo** [comment]
Great work, thanks for this! I wouldn't be against changing the default behavior in a minor or major release.

**Comment by Platane** [comment]
Awesome ! thanks

**Pull request merged**
